apiVersion: v2
name: o-neko
description: A Helm chart for O-Neko
type: application
version: 1.1.4
appVersion: "1.5.2"
sources:
- https://github.com/subshell/o-neko/
dependencies:
  - name: mongodb
    version: 11.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
